[Windows]
configs = ['git', 'nvim']
setup = 'setup.ps1'

[Darwin]
configs = ['git', 'nvim', 'tmux']
setup = 'setup.sh'

[Linux]
configs = ['common', 'git', 'nvim', 'tmux', 'fish', 'omf', 'ctags']
setup = 'setup.sh'
